language:
  - python
python:
  - "3.4"
before_install:
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  - sudo echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
  - sudo apt-get update
  - sudo apt-get install -y libpcre3
  - sudo apt-get install -y oracle-java8-installer
  - sudo update-java-alternatives -s java-8-oracle
install:
  - python setup.py install
script:
  - nosetests
